services:
  api:
    build:
      context: .
      dockerfile: B3.API/B3.API/Dockerfile
    ports:
      - "8080:80"
    networks:
      - app-network

  angular:
    build:
      context: ./cdbWeb
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network
    depends_on:
      - api

networks:
  app-network:
    driver: bridge
