# Nome da PIPELINE
name: Deploy B3.API 

# Define o gatilho da PIPELINE
# Executado sempre que um PUSH for feito na BRANCH main
on:
  push:
    branches:
      - main

# Criando as tarefas / passos da PIPELINE
jobs:
  # 1. Compilação do projeto
  compilacao:
    name: Compilar aplicação
    runs-on: ubuntu-latest

    # passos da compilação
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restaurar as dependências
        run: dotnet restore

      - name: Compilar o projeto
        run: dotnet build B3.API.sln  --configuration Release --no-restore

      - name: Upload da compilação
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./
