name: Build and deploy ASP.Net Core app to Azure Web App - B3

on:
  push:
    branches:
      - main 
  workflow_dispatch:

env:
  DOTNET_ROOT: C:\Program Files\dotnet
  ARTIFACT_DIR: ${{env.DOTNET_ROOT}}/myapp

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Angular dependencies
        working-directory: cdbWeb
        run: npm ci

      - name: Build Angular app
        working-directory: cdbWeb
        run: npm run build -- --configuration=production

      - name: Verify Angular build output
        shell: pwsh
        working-directory: cdbWeb
        run: |
          $indexPath = "dist\cdb-web\browser\index.html"
          if (-not (Test-Path $indexPath)) {
              Write-Error "index.html not found in Angular build output!"
              exit 1
          }
          
          $content = Get-Content $indexPath -Raw
          if ($content.Trim().Length -eq 0) {
              Write-Error "Angular index.html is empty!"
              exit 1
          }
          
          Write-Host "Angular build verified successfully"
          Get-ChildItem "dist\cdb-web\browser" | Format-Table Name, Length

      - name: Prepare wwwroot directory
        shell: pwsh
        run: |
          # Clean existing wwwroot
          Remove-Item -Recurse -Force "B3.API\wwwroot" -ErrorAction SilentlyContinue
          New-Item -ItemType Directory -Path "B3.API\wwwroot" -Force

      - name: Copy Angular assets
        shell: pwsh
        run: |
          $source = "cdbWeb\dist\cdb-web\browser\*"
          $destination = "B3.API\wwwroot"
          
          Copy-Item -Path $source -Destination $destination -Recurse -Force
          
          # Verify copy
          $indexDest = "$destination\index.html"
          if (-not (Test-Path $indexDest)) {
              Write-Error "index.html not found in wwwroot after copy!"
              exit 1
          }
          
          if ((Get-Item $indexDest).Length -eq 0) {
              Write-Error "Copied index.html is empty!"
              exit 1
          }

      - name: Build .NET solution
        run: dotnet build B3.API/B3.API.sln --configuration Release

      - name: Publish .NET application
        shell: pwsh
        run: |
          # Publish with wwwroot preservation
          dotnet publish B3.API/B3.API/B3.API.csproj `
            -c Release `
            -o $env:ARTIFACT_DIR `
            /p:DeleteExistingFiles=false
          
          # Verify published files
          $publishedIndex = "$env:ARTIFACT_DIR\wwwroot\index.html"
          if (-not (Test-Path $publishedIndex)) {
              Write-Error "index.html missing in published output!"
              Get-ChildItem "$env:ARTIFACT_DIR\wwwroot" -Recurse
              exit 1
          }
          
          if ((Get-Item $publishedIndex).Length -eq 0) {
              Write-Error "Published index.html is empty!"
              exit 1
          }

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.ARTIFACT_DIR}}

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ${{env.ARTIFACT_DIR}}

      - name: Verify downloaded artifact
        shell: pwsh
        run: |
          $indexPath = "$env:ARTIFACT_DIR\wwwroot\index.html"
          if (-not (Test-Path $indexPath)) {
              Write-Error "index.html missing in downloaded artifact!"
              exit 1
          }
          
          if ((Get-Item $indexPath).Length -eq 0) {
              Write-Error "Downloaded index.html is empty!"
              exit 1
          }

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8DB310D194E549EDAEE63FFD4ACCE025 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2A355AA9F62F4B6D8BE19857D3969D56 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DC15C30FD6CC4D6A8B1A793499BC115F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'B3'
          slot-name: 'Production'
          package: ${{env.ARTIFACT_DIR}}